# Generated by Django 4.2.4 on 2023-08-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='word',
            name='examples',
        ),
    ]
