# Generated by Django 4.2.4 on 2023-08-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_word_definition_remove_word_examples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('word_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField()),
                ('definition_id', models.IntegerField()),
            ],
        ),
    ]
