# Generated by Django 4.2.4 on 2023-08-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_definitions_examples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definitions',
            name='word_id',
        ),
        migrations.RemoveField(
            model_name='examples',
            name='definition_id',
        ),
        migrations.AddField(
            model_name='definitions',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examples',
            name='definition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.definitions'),
            preserve_default=False,
        ),
    ]
